apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/kle04/manifest-llmops-multi-agents
    targetRevision: main
    path: charts/chatbot-frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
